include:
  - services/databases/postgres.yaml
  - services/databases/redis.yaml
  - services/applications/git-tea.yaml
  - services/applications/n8n.yaml
  - services/applications/proxy-manager.yaml
  - services/applications/adguard-home.yaml
  - services/applications/samba.yaml
  - services/monitoring/portainer.yaml
  - services/monitoring/cadvisor.yaml
  - services/home-assistant/docker-compose.yaml
networks:
  homelab:
    external: true
