include:
  - services/databases/postgres.yaml
  - services/databases/redis.yaml
  - services/applications/git-tea.yaml
  - services/applications/n8n.yaml
  - services/applications/proxy-manager.yaml
  - services/applications/adguard-home.yaml
  - services/applications/samba.yaml
  - services/monitoring/portainer.yaml
networks:
  homelab:
    external: true

# registry:
#   image: registry:latest
#   container_name: registry
#   restart: unless-stopped
#   environment:
#     - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=["*"]
#     - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods=["HEAD,GET,OPTIONS,DELETE"]
#     - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials=["true"]
#     - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers=["Authorization,Accept,Cache-Control"]
#     - REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers=["Docker-Content-Digest"]
#     - REGISTRY_STORAGE_DELETE_ENABLED=["true"]
#   ports:
#     - "5000:5000"
#   volumes:
#     - registry:/var/lib/registry
#   networks:
#     - homelab

# registry-ui:
#   image: joxit/docker-registry-ui:latest
#   ports:
#     - "8088:80"
#   container_name: registry-ui
#   restart: unless-stopped
#   environment:
#     - REGISTRY_TITLE=Local Docker Registry
#     - REGISTRY_URL=http://192.16.0.20:5000
#     - SINGLE_REGISTRY=true
#     - DELETE_IMAGES=true
#     - SHOW_CONTENT_DIGEST=true
#     - SHOW_CATALOG_NB_TAGS=true
#     - CATALOG_MAX_BRANCHES=1
#     - CATALOG_MIN_BRANCHES=1
#     - TAGLIST_PAGE_SIZE=100
#     - REGISTRY_SECURED=false
#     - CATALOG_ELEMENTS_LIMIT=1000
#   depends_on:
#     - registry
# minio:
#   image: minio/minio:latest
#   container_name: minio
#   ports:
#     - "9000:9000" # API S3-compatible
#     - "9002:9001" # Web UI
#   volumes:
#     - minio-data:/data
#   environment:
#     MINIO_ROOT_USER: ${MINIO_ROOT_USER} # Cambia esto en producción
#     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} # Cambia esto en producción
#   command: server --console-address ":9001" /data
#   restart: unless-stopped
#   networks:
#     - homelab

