services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: --http-enabled
    networks:
      - home-lab

  proxy-manager:
    container_name: proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxy-manager-data:/data
      - proxy-manager-letsencrypt:/etc/letsencrypt
    networks:
      - home-lab

  adguard-home:
    container_name: adguard-home
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '85:85/tcp'
      - '853:853/tcp'
      - '784:784/udp'
      - '853:853/udp'
      - '8853:8853/udp'
      - '5443:5443/tcp'
      - '5443:5443/udp'
      - '3000:3000'
    volumes:
      - adguard-home:/opt/adguardhome/
    networks:
      - home-lab

  samba:
    container_name: samba
    image: dperson/samba # no hay tag con versiones, solo latest
    restart: unless-stopped
    command: '-u "gumonet;Gumonet01" -s "backup;/backup;yes;no" -s "data;/data;yes;no" '
    stdin_open: true
    tty: true
    environment:
      - TZ=America/Mexico_City
    volumes:
      - ~/Backup:/backup
      - ~/Data:/data
    ports:
      - 139:139
      - 445:445
    networks:
      - home-lab



  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./registry:/var/lib/registry
    networks:
      - home-lab

networks:
  home-lab:
    driver: bridge
volumes:
    portainer_data:
    proxy-manager-data:
    proxy-manager-letsencrypt:
    adguard-home:
    registry: