services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__actions__ENABLED=true
      - GITEA__runner__ENABLED=true
    volumes:
      - gitea:/data
    ports:
      - "3002:3000" # Web
      - "2222:22" # SSH Git
    networks:
      - homelab

  gitea-runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    restart: unless-stopped
    depends_on:
      - gitea
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitea-runner-data:/data
    environment:
      - GITEA_INSTANCE_URL=http://192.16.0.20:3002
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_REGISTRATION_TOKEN}
    networks:
      - homelab

volumes:
  gitea:
  gitea-runner-data:
