services:
  proxy-manager:
    container_name: proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - proxy-manager-data:/data
      - proxy-manager-letsencrypt:/etc/letsencrypt
    networks:
      - homelab
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  proxy-manager-data:
  proxy-manager-letsencrypt:
